import type { Metadata } from 'next';
import './globals.css';
import 'pretendard/dist/web/static/pretendard.css';

export const metadata: Metadata = {
  title: 'Next Trello',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ko">
      <body className={'antialiased h-full'}>{children}</body>
    </html>
  );
}
